#server
server:
  port: 8083
#logging
logging:
  level:
    root: DEBUG
#db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/register-account?useSSL=false
    password: funda123!
    username: funda
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect