version: "3"

services:
  #database
  mysql:
    image: mysql:latest
    container_name: funda-mysql
    environment:
      - MYSQL_DATABASE=register-account
      - MYSQL_USER=funda
      - MYSQL_PASSWORD=funda123!
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - funda
#account register app
  register-account:
    env_file: /home/boss/IdeaProjects/register-account/src/main/docker/mysql/.env
    build:
      context: /home/boss/IdeaProjects/register-account
      dockerfile: Dockerfile
    restart: on-failure
    container_name: register-account-app
    depends_on:
      - mysql
    volumes:
      -  /home/boss/IdeaProjects/register-account/src/main/docker/mysql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/register-account?useSSL=false
      - spring.datasource.username=funda
      - spring.datasource.password=funda123!
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.hibernate.ddl-auto=create
    expose:
      - 8082
networks:
  funda:
    driver: bridge