version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: funda-mysql
    environment:
      - MYSQL_DATABASE=register-account
      - MYSQL_USER=funda
      - MYSQL_PASSWORD=funda123!
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - funda
networks:
  funda:
    driver: bridge